import test from "node:test";
import assert from "node:assert/strict";
import { CATALOG_DIAGNOSTICS, REAL_COURSES } from "../data/catalog";
import { decide } from "./engine";

test("approved policy answers are sourced and do not invent cashback", () => { const d = decide([{ role: "user", content: "Do I get cashback?" }], "website"); assert.match(d.answer, /UNKNOWN/); assert.deepEqual(d.sourceProvenance, ["data/policies.ts:verified-policy-snapshot"]); });
test("real catalog is loaded and joined without silent mismatch", () => { assert.equal(CATALOG_DIAGNOSTICS.factual_course_count, 243); assert.equal(CATALOG_DIAGNOSTICS.intelligence_course_count, 243); assert.equal(CATALOG_DIAGNOSTICS.joined_count, 243); assert.deepEqual(CATALOG_DIAGNOSTICS.unmatched_ids, []); assert.deepEqual(CATALOG_DIAGNOSTICS.unmatched_slugs, []); assert.equal(new Set(REAL_COURSES.map(course => course.id)).size, REAL_COURSES.length); });
test("current request retrieves a real prerequisite-free beginner course", () => { const d = decide([{ role: "user", content: "I am an architecture beginner and want to learn AI" }], "website"); assert.equal(d.state, "RECOMMENDATION"); assert.ok(d.primary); assert.notEqual(d.primary?.id, "mock-3"); assert.ok(d.primary?.prerequisites.length === 0); assert.ok(d.primary?.reasonCodes.includes("GOAL_MATCH")); });
test("channel output is shorter for Instagram", () => { const d = decide([{ role: "user", content: "Is it live and do I get a certificate?" }], "instagram"); assert.ok(d.answer.endsWith(".")); assert.equal(d.state, "POLICY"); });
test("regression A recommends from the current architecture AI request", () => { const d = decide([{ role: "user", content: "I'm an architect and I want to learn how to use AI in my design workflow, but I'm a beginner. What would you recommend?" }], "website"); assert.equal(d.state, "RECOMMENDATION"); assert.equal(d.conversation_state, "RECOMMENDATION"); assert.equal(d.nextBestAction, "SHOW_RECOMMENDATION"); assert.ok(d.primary); assert.ok(d.primary?.reasonCodes.includes("GOAL_MATCH")); });
test("regression B answers Rhino follow-up directly and preserves history", () => { const d = decide([{ role: "user", content: "I'm an architect and I want to learn how to use AI in my design workflow, but I'm a beginner. What would you recommend?" }, { role: "user", content: "I already use Rhino. Would that change your recommendation?" }], "website"); assert.match(d.answer, /^Yes —/); assert.match(d.answer, /software experience/); assert.equal(d.profile.profession, "architecture"); assert.deepEqual(d.profile.goals, ["artificial intelligence"]); assert.equal(d.profile.software_experience[0].software, "Rhino"); assert.equal(d.profile.software_experience[0].status, "uses"); });
test("regression C treats negative preferences as constraints and keeps the current AI goal", () => { const messages = [{ role: "user" as const, content: "I'm an architect and I want to learn how to use AI in my design workflow, but I'm a beginner. What would you recommend?" }, { role: "user" as const, content: "I already use Rhino. Would that change your recommendation?" }, { role: "user" as const, content: "Actually, I don't want to learn Grasshopper or computational design. I only want AI tools that I can apply directly to architecture." }]; const d = decide(messages, "website"); assert.deepEqual(d.profile.excluded_tools, ["Grasshopper"]); assert.deepEqual(d.profile.excluded_topics, ["computational design"]); assert.deepEqual(d.profile.goals, ["artificial intelligence"]); assert.ok(d.primary); assert.ok(d.candidates.every(c => !/grasshopper|computational design/i.test(`${c.title} ${c.topic} ${c.searchableText}`))); assert.ok(d.reasonCodes.includes("EXCLUDED")); });
test("retrieval covers real AI, Grasshopper, Rhino, Midjourney and fabrication language", () => { for (const query of ["AI architecture", "Grasshopper", "Rhino", "Midjourney", "robotic fabrication"]) { const d = decide([{ role: "user", content: query }], "website"); assert.ok(d.candidate_count > 0, query); assert.ok(d.candidates.length <= 10); } });
test("blank requirements mean no prerequisite and difficulty alone is not one", () => { const blank = REAL_COURSES.find(course => course.prerequisites.length === 0); assert.ok(blank); assert.equal(blank?.requires_previous, "UNKNOWN"); assert.ok(blank?.level); });
test("version numbers do not create prerequisite chains", () => { const versioned = REAL_COURSES.find(course => course.version); assert.ok(versioned); assert.equal(versioned?.requires_previous, "UNKNOWN"); });
test("recommendation facts have factual and intelligence provenance", () => { const d = decide([{ role: "user", content: "I want AI visualization training for architecture" }], "website"); assert.ok(d.primary); assert.equal(d.primary?.factual_source, "data/snapshots/all-courses-with-all-details.csv"); assert.equal(d.primary?.intelligence_source, "data/snapshots/course_intelligence.json"); assert.ok(d.primary?.slug); assert.match(d.primary?.url ?? "", /^https:\/\/paacademy\.com\/course\//); });
