import test from "node:test";
import assert from "node:assert/strict";
import { CATALOG_DIAGNOSTICS, REAL_COURSES } from "../data/catalog";
import { decide } from "./engine";

test("approved policy answers are sourced and do not invent cashback", () => { const d = decide([{ role: "user", content: "Do I get cashback?" }], "website"); assert.match(d.answer, /cannot confirm a cashback offer/i); assert.equal(d.question_coverage[0].status, "UNKNOWN"); });
test("real catalog is loaded and joined without silent mismatch", () => { assert.equal(CATALOG_DIAGNOSTICS.factual_course_count, 243); assert.equal(CATALOG_DIAGNOSTICS.intelligence_course_count, 243); assert.equal(CATALOG_DIAGNOSTICS.joined_count, 243); assert.deepEqual(CATALOG_DIAGNOSTICS.unmatched_ids, []); assert.deepEqual(CATALOG_DIAGNOSTICS.unmatched_slugs, []); assert.equal(new Set(REAL_COURSES.map(course => course.id)).size, REAL_COURSES.length); });
test("current request retrieves a real prerequisite-free beginner course", () => { const d = decide([{ role: "user", content: "I am an architecture beginner and want to learn AI" }], "website"); assert.equal(d.state, "RECOMMENDATION"); assert.ok(d.primary); assert.notEqual(d.primary?.id, "mock-3"); assert.ok(d.primary?.prerequisites.length === 0); assert.ok(d.primary?.reasonCodes.includes("GOAL_MATCH")); });
test("channel output is shorter for Instagram", () => { const d = decide([{ role: "user", content: "Is it live and do I get a certificate?" }], "instagram"); assert.ok(d.answer.endsWith(".")); assert.equal(d.state, "POLICY"); });
test("regression A recommends from the current architecture AI request", () => { const d = decide([{ role: "user", content: "I'm an architect and I want to learn how to use AI in my design workflow, but I'm a beginner. What would you recommend?" }], "website"); assert.equal(d.state, "RECOMMENDATION"); assert.equal(d.conversation_state, "RECOMMENDATION"); assert.equal(d.nextBestAction, "SHOW_RECOMMENDATION"); assert.ok(d.primary); assert.ok(d.primary?.reasonCodes.includes("GOAL_MATCH")); });
test("regression B answers Rhino follow-up directly and preserves history", () => { const d = decide([{ role: "user", content: "I'm an architect and I want to learn how to use AI in my design workflow, but I'm a beginner. What would you recommend?" }, { role: "user", content: "I already use Rhino. Would that change your recommendation?" }], "website"); assert.match(d.answer, /^No —/); assert.match(d.answer, /Rhino is useful compatibility context/); assert.equal(d.profile.profession, "architecture"); assert.deepEqual(d.profile.goals, ["artificial intelligence"]); assert.equal(d.profile.software_experience[0].software, "Rhino"); assert.equal(d.profile.software_experience[0].status, "uses"); });
test("regression C treats negative preferences as constraints and keeps the current AI goal", () => { const messages = [{ role: "user" as const, content: "I'm an architect and I want to learn how to use AI in my design workflow, but I'm a beginner. What would you recommend?" }, { role: "user" as const, content: "I already use Rhino. Would that change your recommendation?" }, { role: "user" as const, content: "Actually, I don't want to learn Grasshopper or computational design. I only want AI tools that I can apply directly to architecture." }]; const d = decide(messages, "website"); assert.deepEqual(d.profile.excluded_tools, ["Grasshopper"]); assert.deepEqual(d.profile.excluded_topics, ["computational design"]); assert.ok(d.profile.goals.includes("artificial intelligence")); assert.ok(d.primary); assert.ok(d.candidates.every(c => !/grasshopper|computational design/i.test(`${c.title} ${c.topic} ${c.searchableText}`))); assert.ok(d.reasonCodes.includes("EXCLUDED")); });
test("retrieval covers real AI, Grasshopper, Rhino, Midjourney and fabrication language", () => { for (const query of ["AI architecture", "Grasshopper", "Rhino", "Midjourney", "robotic fabrication"]) { const d = decide([{ role: "user", content: query }], "website"); assert.ok(d.candidate_count > 0, query); assert.ok(d.candidates.length <= 10); } });
test("blank requirements mean no prerequisite and difficulty alone is not one", () => { const blank = REAL_COURSES.find(course => course.prerequisites.length === 0); assert.ok(blank); assert.equal(blank?.requires_previous, "UNKNOWN"); assert.ok(blank?.level); });
test("version numbers do not create prerequisite chains", () => { const versioned = REAL_COURSES.find(course => course.version); assert.ok(versioned); assert.equal(versioned?.requires_previous, "UNKNOWN"); });
test("recommendation facts have factual and intelligence provenance", () => { const d = decide([{ role: "user", content: "I want AI visualization training for architecture" }], "website"); assert.ok(d.primary); assert.equal(d.primary?.factual_source, "data/snapshots/all-courses-with-all-details.csv"); assert.equal(d.primary?.intelligence_source, "data/snapshots/course_intelligence.json"); assert.ok(d.primary?.slug); assert.match(d.primary?.url ?? "", /^https:\/\/paacademy\.com\/course\//); });
test("generic negation never creates a positive fabrication or coding goal", () => { const d = decide([{ role: "user", content: "I don't really care about fabrication or coding." }], "website"); assert.ok(d.profile.negative_preferences.includes("fabrication")); assert.ok(d.profile.negative_preferences.includes("coding")); assert.ok(!d.profile.goals.includes("fabrication")); assert.ok(!d.profile.goals.includes("coding")); });
test("comparison and conversion use explicit intent and NBA", () => { const compareDecision = decide([{ role: "user", content: "Compare the top recommendation with the alternative. Which one is more aligned?" }], "website"); assert.equal(compareDecision.primaryIntent, "COURSE_COMPARISON"); assert.equal(compareDecision.nextBestAction, "COMPARE_COURSES"); assert.match(compareDecision.answer, /vs/); const conversion = decide([{ role: "user", content: "I want to enroll. What should I do?" }], "website"); assert.ok(["PURCHASE_INTENT", "REGISTRATION"].includes(conversion.primaryIntent)); assert.equal(conversion.state, "CONVERSION"); assert.equal(conversion.nextBestAction, "PROVIDE_PURCHASE_PATH"); assert.ok(!/purchase has completed/i.test(conversion.answer)); });
test("eight-turn QA journey preserves profile, covers questions and reaches conversion", () => { const turns = ["I'm an architect and a complete beginner. I want to use AI directly in architectural concept design. What should I take?", "I already use Rhino quite comfortably. Does that change your recommendation?", "But I don't want to learn Grasshopper or computational design. I only want AI tools that I can apply directly to architecture.", "My main goal is early-stage concept generation and exploring design ideas faster. I don't really care about fabrication or coding.", "Compare your top recommendation with the alternative. Which one is more aligned with the goal I described?", "I probably can't attend live. Can I watch the recording later, and would I still get a certificate?", "What's the current price? Are there any discounts, promo codes, or cashback I can use?", "Sounds good. I want to enroll. What should I do?"]; let messages: { role: "user"; content: string }[] = []; const decisions = turns.map(content => { messages = [...messages, { role: "user", content }]; return decide(messages, "website"); }); const final = decisions.at(-1)!; assert.equal(decisions[0].primaryIntent, "COURSE_RECOMMENDATION"); assert.equal(decisions[2].profile.excluded_tools.includes("Grasshopper"), true); assert.equal(decisions[3].profile.negative_preferences.includes("fabrication"), true); assert.equal(decisions[4].nextBestAction, "COMPARE_COURSES"); assert.equal(decisions[5].primaryIntent, "POLICY_QUESTION"); assert.equal(decisions[6].question_coverage.length, 4); assert.equal(final.state, "CONVERSION"); assert.equal(final.nextBestAction, "PROVIDE_PURCHASE_PATH"); assert.match(final.answer, /paacademy\.com\/course/); assert.ok(final.profile.goals.length > 0); });
test("paraphrase and Turkish semantic cases remain covered", () => { const cases = [{ text: "I'm not interested in fabrication.", field: "negative" }, { text: "I'd rather avoid coding.", field: "negative" }, { text: "I know Rhino already.", field: "software" }, { text: "Bu iki kursu karşılaştır.", field: "comparison" }, { text: "Bu kursa kayıt olmak istiyorum, ne yapmalıyım?", field: "conversion" }]; for (const item of cases) { const d = decide([{ role: "user", content: item.text }], "website"); if (item.field === "negative") assert.ok(d.profile.negative_preferences.length > 0); if (item.field === "software") assert.equal(d.profile.software_experience[0].status, "uses"); if (item.field === "comparison") assert.equal(d.primaryIntent, "COURSE_COMPARISON"); if (item.field === "conversion") assert.equal(d.state, "CONVERSION"); } });

test("profile keeps interaction meta out and separates hard exclusions from strong negatives", () => { const d = decide([{ role: "user", content: "I want an AI course recommendation, but I don't want to learn Grasshopper or computational design. I don't really care about fabrication or coding. I want AI tools applied directly to architecture." }], "website"); const profileText = JSON.stringify(d.profile).toLowerCase(); for (const meta of ["course recommendation", "course comparison", "policy", "commercial terms", "enrollment"]) assert.ok(!profileText.includes(meta)); assert.deepEqual(d.profile.hard_exclusions, ["Grasshopper", "computational design"]); assert.ok(d.profile.strong_negative_preferences.includes("fabrication")); assert.ok(d.profile.strong_negative_preferences.includes("coding")); assert.ok(d.profile.goals.includes("artificial intelligence")); assert.ok(d.profile.desired_outcomes.includes("AI-assisted architectural application")); });

test("context-only Rhino is retained without forcing a recommendation change", () => { const first = decide([{ role: "user", content: "I'm an architect and beginner. I want to apply AI directly to architecture." }], "website"); const second = decide([{ role: "user", content: "I'm an architect and beginner. I want to apply AI directly to architecture." }, { role: "user", content: "I already use Rhino. Would that change your recommendation?" }], "website"); assert.equal(second.primary?.id, first.primary?.id); assert.equal(second.stability_applied, true); assert.equal(second.recommendation_changed, false); assert.equal(second.profile.software_experience[0].status, "uses"); assert.ok(second.profile.context_only.includes("Rhino")); });

test("specific current goals discriminate ranking and retain explainable score components", () => { const d = decide([{ role: "user", content: "I want early-stage concept generation and to explore architectural design ideas faster with AI." }], "website"); assert.ok(d.primary); assert.ok(d.primary?.scoreComponents.GOAL_MATCH > 0); assert.ok(Object.keys(d.primary?.scoreComponents ?? {}).some(code => ["GOAL_MATCH", "DESIRED_OUTPUT_MATCH", "TOPIC_MATCH"].includes(code))); assert.ok(d.candidates.length > 1); assert.ok(new Set(d.candidates.map(candidate => candidate.score)).size > 1); assert.ok(d.candidates.every(candidate => !/grasshopper|computational design/i.test(`${candidate.title} ${candidate.topic}`) || !d.profile.hard_exclusions.length)); });

test("recommendation changes always carry reasons and comparisons expose real differentiators", () => { const messages = [{ role: "user" as const, content: "I want AI for architectural concept design." }, { role: "user" as const, content: "Actually, I only want early-stage concept generation and faster design exploration; exclude computational design." }]; const changed = decide(messages, "website"); if (changed.recommendation_changed) assert.ok(changed.change_reasons.length > 0); const comparison = decide([...messages, { role: "user" as const, content: "Compare the top recommendation with the alternative." }], "website"); assert.ok(comparison.comparison_differentiators.length > 0); assert.ok(!/GOAL_MATCH|LEVEL_MATCH|SOFTWARE_MATCH/.test(comparison.answer)); });

test("response plan, state and next action stay synchronized", () => { const d = decide([{ role: "user", content: "I am an architect and beginner. Recommend an AI course." }], "website"); assert.equal(d.conversation_state, "RECOMMENDATION"); assert.equal(d.state, "RECOMMENDATION"); assert.equal(d.nextBestAction, "SHOW_RECOMMENDATION"); assert.equal(d.response_plan.answer_type, "recommendation"); assert.deepEqual(d.missingInformation, []); });

test("course fingerprints provide bounded evidence-grounded retrieval", () => { const d = decide([{ role: "user", content: "I want early-stage architectural concept generation with AI." }], "website"); assert.ok(d.retrieval_count >= 15 && d.retrieval_count <= 30); assert.ok(d.candidates.every(course => course.matchedEvidence.length > 0 || course.evidenceStrength === "NONE")); assert.ok(d.candidates.some(course => course.scoreComponents.workflow_stage_score > 0)); assert.ok(new Set(d.candidates.map(course => course.score)).size > 1); });

test("hard negative and format signals remain separate from fit goals", () => { const d = decide([{ role: "user", content: "I use Rhino every day but that is not what I want the course to focus on. I would rather avoid scripting and fabrication. I cannot join Zoom; can I watch the recording?" }], "website"); assert.ok(d.profile.context_only.includes("Rhino")); assert.ok(d.profile.strong_negative_preferences.includes("coding")); assert.ok(d.profile.strong_negative_preferences.includes("fabrication")); assert.ok(d.profile.format_preferences.includes("recorded")); assert.ok(!d.profile.goals.includes("coding")); assert.ok(!d.profile.goals.includes("fabrication")); });

test("natural responses do not leak ranking internals or unsupported comparison language", () => { const d = decide([{ role: "user", content: "I want AI for concept work, not rendering." }], "website"); assert.ok(!/SPECIFIC_EVIDENCE|GOAL_MATCH|reason code|blank requirements field|catalog snapshot|semantic ranking|listed course evidence/i.test(d.answer)); const comparison = decide([{ role: "user", content: "Compare the top recommendation with the alternative." }], "website"); assert.ok(!/listed course evidence|semantic ranking|SPECIFIC_EVIDENCE|GOAL_MATCH/i.test(comparison.answer)); });

test("English and Turkish paraphrases preserve the same architecture intent", () => { const english = decide([{ role: "user", content: "I am mostly trying to generate architectural ideas at the beginning of a project." }], "website"); const turkish = decide([{ role: "user", content: "Mimarım ve başlangıç seviyesindeyim. Yapay zekayı konsept tasarım sürecimde kullanmak istiyorum." }], "website"); assert.ok(english.profile.goals.includes("architectural concept design") || english.profile.goals.includes("early-stage concept generation")); assert.ok(turkish.profile.profession === "architecture"); assert.ok(turkish.profile.goals.includes("artificial intelligence")); });

test("stability exposes ranked and selected primaries without preserving an invalid course", () => { const d = decide([{ role: "user", content: "I want AI for architectural concept design." }, { role: "user", content: "I already use Rhino. Would that change your recommendation?" }], "website"); assert.ok(d.ranked_primary); assert.ok(d.selected_primary); assert.equal(d.selected_primary?.id, d.primary?.id); assert.equal(d.stability_override, d.ranked_primary?.id !== d.selected_primary?.id); assert.equal(d.recommendation_changed, false); });

test("V0.4.1 active alignment prioritizes the latest specific objective", () => { const d = decide([{ role: "user", content: "I want AI for architecture." }, { role: "user", content: "My active goal is early-stage concept generation and faster exploration." }], "website"); assert.equal(d.active_primary_goal, "early-stage concept generation"); assert.ok(d.primary); assert.ok(d.primary?.activeGoalAlignment.label !== "NO_MATCH"); assert.ok(d.primary?.scoreComponents.workflow_stage_score > 0); assert.ok(d.candidates.some(course => course.activeGoalAlignment.label === "CENTRAL_MATCH")); });

test("negative centrality changes penalty without globally suppressing categories", () => { const negative = decide([{ role: "user", content: "I want AI for architecture, but I do not care about fabrication." }], "website"); const positive = decide([{ role: "user", content: "I want AI for fabrication and 3D printing." }], "website"); assert.ok(negative.profile.strong_negative_preferences.includes("fabrication")); assert.ok(negative.candidates.every(course => course.negativeAlignment.centrality.every(level => level !== "HIGH") || course.scoreComponents.negative_penalty < 0)); assert.ok(positive.candidates.some(course => course.workflowAlignment.primaryStages.includes("fabrication") || /fabrication|robot|3d printing/i.test(`${course.title} ${course.topic} ${course.searchableText}`))); });

test("counter-goals remain eligible and alter semantic retrieval", () => { const modeling = decide([{ role: "user", content: "I want AI for detailed Rhino modeling." }], "website"); const animation = decide([{ role: "user", content: "I want AI animation and cinematic workflows." }], "website"); const grasshopper = decide([{ role: "user", content: "I want AI with Grasshopper and computational design." }], "website"); assert.ok(modeling.candidates.some(course => /model|rhino|subd/i.test(`${course.title} ${course.topic}`))); assert.ok(animation.candidates.some(course => /animation|cinematic|motion/i.test(`${course.title} ${course.topic} ${course.searchableText}`))); assert.ok(grasshopper.profile.hard_exclusions.length === 0); assert.ok(grasshopper.candidates.some(course => /grasshopper|parametric|computational/i.test(`${course.title} ${course.topic} ${course.searchableText}`))); });

test("true profile delta separates current additions from preserved history", () => { const d = decide([{ role: "user", content: "I am an architect and beginner. I want AI." }, { role: "user", content: "I want early-stage concept generation." }], "website"); assert.ok(d.profile_delta.added.some(fact => fact.value === "early-stage concept generation")); assert.ok(d.profile_delta.preserved.some(fact => fact.value === "artificial intelligence" || fact.value === "architecture")); assert.ok(!d.profile_delta.added.some(fact => fact.value === "course recommendation" || fact.value === "commercial terms")); });
test("V0.4.2 alternative selection exposes fit-first utility and directional comparison", () => { const d = decide([{ role: "user", content: "I'm an architect and beginner. My main goal is early-stage concept generation and exploring design ideas faster." }], "website"); assert.ok(d.primary); assert.ok(d.alternative); assert.ok(d.alternative_candidate_pool?.length); assert.ok(d.alternative_candidate_pool?.some(item => item.accepted_or_rejected === "ACCEPTED")); assert.ok(d.alternative_candidate_pool?.every(item => item.alternative_utility !== undefined)); const comparison = decide([{ role: "user", content: "I'm an architect and beginner. I want early-stage AI concept ideation." }, { role: "user", content: "Compare the top recommendation with the alternative. Which one is more aligned with the goal I described?" }], "website"); assert.equal(comparison.primaryIntent, "COURSE_COMPARISON"); assert.ok(comparison.comparison_difference); assert.ok(comparison.answer.includes("vs")); assert.ok(!/GOAL_MATCH|semantic alignment|hard exclusion/i.test(comparison.answer)); });
test("V0.4.2 context-only follow-up polarity and stability are synchronized", () => { const d = decide([{ role: "user", content: "I want AI for architectural concept design." }, { role: "user", content: "I already use Rhino quite comfortably. Does that change your recommendation?" }], "website"); assert.match(d.answer, /^No —/); assert.equal(d.recommendation_changed, false); assert.equal(d.stability_override, d.ranked_primary?.id !== d.selected_primary?.id); assert.ok(!/€|recording|checkout/i.test(d.answer)); });
test("V0.4.2 alternative behavior changes with counter-goals", () => { const cases = ["I want AI for detailed Rhino modeling.", "I want AI animation and cinematic workflows.", "I want AI for fabrication and robotic production.", "I want an AI architectural competition workflow.", "I want Grasshopper and AI for computational design."]; for (const text of cases) { const d = decide([{ role: "user", content: text }], "website"); assert.ok(d.primary); assert.ok(d.alternative); assert.ok(d.alternative_candidate_pool?.some(item => item.accepted_or_rejected === "ACCEPTED" || item.course === d.alternative?.title)); } });
