export type Channel = "website" | "whatsapp" | "instagram";
export type ConversationState = "DISCOVERY" | "QUALIFICATION" | "RECOMMENDATION" | "POLICY";
export type Intent = "course_discovery" | "course_comparison" | "policy_question" | "purchase_intent" | "general";
export type Course = { id: string; title: string; format: "Workshop" | "Lecture" | "Conference" | "Pre-Recorded"; level: string; topic: string; upcoming: boolean; prerequisites: string[]; priceEur: number; memberIncluded?: boolean; url: string };
export type ScoredCourse = Course & { score: number; reasonCodes: string[] };
export type SoftwareExperience = { software: string; status: "uses" | "learning"; level?: string; source: "current_request" | "history" };
export type Profile = { profession?: string; level?: string; goals: string[]; software_experience: SoftwareExperience[]; negative_preferences: string[]; excluded_topics: string[]; excluded_tools: string[] };
export type Decision = { primaryIntent: Intent; secondaryIntent: string | null; state: ConversationState; conversation_state: ConversationState; entities: Record<string, string>; profile: Profile; missingInformation: string[]; nextBestAction: string; candidates: ScoredCourse[]; primary: ScoredCourse | null; alternative: ScoredCourse | null; confidence: "HIGH" | "MEDIUM" | "LOW"; reasonCodes: string[]; sourceProvenance: string[]; answer: string; recommendation_changed: boolean; previous_primary: string | null; new_primary: string | null; change_reasons: string[] };
export type ChatMessage = { role: "user" | "assistant"; content: string };
